name: Publish CFn templates
on:
  push:
    branches:
      - main
  workflow_dispatch: {}
env:
  #BSS_TEMPLATE_BUCKET_NAME: supabase-on-aws
  BSS_TEMPLATE_BUCKET_NAME: 'supabase-on-aws-${AWS::Region}'
  BSS_FILE_ASSET_BUCKET_NAME: 'supabase-on-aws-${AWS::Region}'
  BSS_FILE_ASSET_REGION_SET: us-east-1, us-west-2
  BSS_FILE_ASSET_PREFIX: latest/

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # needed to interact with GitHub's OIDC Token endpoint.
      contents: read
    steps:

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.FILE_PUBLISHING_ROLE }}
          aws-region: us-west-2

      - name: Checkout
        uses: actions/checkout@v2

      - name: node.js setup
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: yarn install --check-files

      #- name: cdk build
      #  run: npx projen build

      - name: cdk synth
        run: $(npm bin)/cdk synth --no-version-reporting

      - name: Publish assets
        run: npx cdk-assets publish --path cdk.out/Supabase.assets.json --verbose
