name: Publish Kong Image
on:
  push:
    branches:
      - main
  workflow_dispatch: {}
env:
  ECR_PUBLIC_REGISTRY: public.ecr.aws/u3p7q2r8
  IMAGE_NAME: supabase-kong

jobs:
  ecr_public:
    name: ECR Public
    runs-on: ubuntu-latest
    permissions:
      id-token: write # needed to interact with GitHub's OIDC Token endpoint.
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: src/containers/kong/**/*

      - name: Set up QEMU
        if: env.GIT_DIFF
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        if: env.GIT_DIFF
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS credentials
        if: env.GIT_DIFF
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.ECR_PUBLIC_ROLE }}
          aws-region: us-east-1

      - name: Login to ECR Public
        if: env.GIT_DIFF
        run: aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ env.ECR_PUBLIC_REGISTRY }}

      #- name: Extract metadata (tags, labels) for Docker
      #  id: meta
      #  uses: docker/metadata-action@v4
      #  with:
      #    images: ${{ env.ECR_PUBLIC_REGISTRY }}/${{ env.IMAGE_NAME }}
      #    flavor: |
      #      latest=true
      #    tags: |
      #      type=raw,value=lates

      - name: Build and push
        if: env.GIT_DIFF
        uses: docker/build-push-action@v3
        with:
          context: ./src/containers/kong
          file: ./src/containers/kong/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.ECR_PUBLIC_REGISTRY }}/${{ env.IMAGE_NAME }}:latest