name: Publish CFn templates
on:
  push:
    branches:
      - main
  workflow_dispatch: {}
env:
  BSS_FILE_ASSET_BUCKET_NAME: 'supabase-on-aws-${AWS::Region}'
  BSS_FILE_ASSET_REGION_SET: us-east-1,us-west-2,eu-west-1,ap-northeast-1,ap-southeast-1
  BSS_FILE_ASSET_PREFIX: latest/

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # needed to interact with GitHub's OIDC Token endpoint.
      contents: read
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            src/**/*
            .projenrc.js

      - name: node.js setup
        if: env.GIT_DIFF
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        if: env.GIT_DIFF
        run: yarn install --check-files

      - name: Configure AWS credentials
        if: env.GIT_DIFF
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.CDK_PUBLISHING_ROLE }}
          aws-region: us-west-2

      - name: cdk synth
        if: env.GIT_DIFF
        run: $(npm bin)/cdk synth --no-version-reporting

      - name: remove old template
        if: env.GIT_DIFF
        run: |
          region_list=(${BSS_FILE_ASSET_REGION_SET//,/ })
          for region in ${region_list[@]}; do
              bucket_name=(${BSS_FILE_ASSET_BUCKET_NAME//\$\{AWS::Region\}/$region})
              aws s3 rm s3://$bucket_name/${BSS_FILE_ASSET_PREFIX}Supabase.template.json
          done

      - name: Publish assets
        if: env.GIT_DIFF
        run: npx cdk-assets publish --path cdk.out/Supabase.assets.json --verbose
